export ENABLE_DEBUG_DIS64=1
export ENABLE_DEBUG_INPUT_BFD=1
export ENABLE_DEBUG_INPUT_DIS=1
export ENABLE_DEBUG_EXE=1
export ENABLE_DEBUG_ANALYSE=1
export ENABLE_DEBUG_ANALYSE_PATHS=1
export ENABLE_DEBUG_ANALYSE_PHI=1
export ENABLE_DEBUG_OUTPUT=1

echo test10_ll
../../../test/dis64 test10_ll.o 2>&1 | grep "END - FINISHED PROCESSING"
